-- Insert data into shoe_characteristics table
INSERT INTO public.shoe_characteristics (
    product_id, product_name, size, color, material, weight, brand, price, description
)
VALUES
    (1, 'Nike Air Max', 10.0, 'Red', 'Leather', 0.80, 'Nike', 129.99, 'The Nike Air Max offers great cushioning and stylish design.'),
    (2, 'Nike Air Max', 9.5, 'Red', 'Leather', 0.80, 'Nike', 129.99, 'The Nike Air Max offers great cushioning and stylish design.'),
    (3, 'Adidas Ultraboost', 10.0, 'Black', 'Mesh', 0.70, 'Adidas', 180.00, 'The Adidas Ultraboost is known for its comfort and breathability.'),
    (4, 'Adidas Ultraboost', 9.5, 'Black', 'Mesh', 0.70, 'Adidas', 180.00, 'The Adidas Ultraboost is known for its comfort and breathability.'),
    (5, 'Puma RS-X', 10.0, 'Blue', 'Synthetic', 0.90, 'Puma', 110.00, 'The Puma RS-X combines bold styling with durable performance.'),
    (6, 'Puma RS-X', 9.5, 'Blue', 'Synthetic', 0.90, 'Puma', 110.00, 'The Puma RS-X combines bold styling with durable performance.'),
    (7, 'Puma RS-X', 9.5, 'Red', 'Synthetic', 0.90, 'Puma', 110.00, 'The Puma RS-X combines bold styling with durable performance.'),
    (8, 'Nike Air Max', 11.0, 'Red', 'Leather', 0.80, 'Nike', 129.99, 'The Nike Air Max offers great cushioning and stylish design.'),
    (9, 'Nike Air Max', 8.5, 'Blue', 'Leather', 0.80, 'Nike', 129.99, 'The Nike Air Max offers great cushioning and stylish design.'),
    (10, 'Nike Air Max', 10.0, 'White', 'Leather', 0.80, 'Nike', 129.99, 'The Nike Air Max offers great cushioning and stylish design.'),
    (11, 'Adidas Ultraboost', 11.0, 'Black', 'Mesh', 0.70, 'Adidas', 180.00, 'The Adidas Ultraboost is known for its comfort and breathability.'),
    (12, 'Adidas Ultraboost', 8.5, 'White', 'Mesh', 0.70, 'Adidas', 180.00, 'The Adidas Ultraboost is known for its comfort and breathability.'),
    (13, 'Adidas Ultraboost', 10.0, 'Grey', 'Mesh', 0.70, 'Adidas', 180.00, 'The Adidas Ultraboost is known for its comfort and breathability.'),
    (14, 'Puma RS-X', 11.0, 'Blue', 'Synthetic', 0.90, 'Puma', 110.00, 'The Puma RS-X combines bold styling with durable performance.'),
    (15, 'Puma RS-X', 8.5, 'Red', 'Synthetic', 0.90, 'Puma', 110.00, 'The Puma RS-X combines bold styling with durable performance.'),
    (16, 'Puma RS-X', 10.0, 'White', 'Synthetic', 0.90, 'Puma', 110.00, 'The Puma RS-X combines bold styling with durable performance.'),
    (17, 'Reebok Classic', 10.0, 'White', 'Leather', 0.75, 'Reebok', 85.00, 'The Reebok Classic delivers timeless style and everyday comfort.'),
    (18, 'Reebok Classic', 9.5, 'White', 'Leather', 0.75, 'Reebok', 85.00, 'The Reebok Classic delivers timeless style and everyday comfort.'),
    (19, 'Reebok Classic', 11.0, 'Black', 'Leather', 0.75, 'Reebok', 85.00, 'The Reebok Classic delivers timeless style and everyday comfort.'),
    (20, 'Reebok Classic', 8.5, 'Grey', 'Leather', 0.75, 'Reebok', 85.00, 'The Reebok Classic delivers timeless style and everyday comfort.'),
    (21, 'New Balance 990', 10.0, 'Grey', 'Suede', 0.85, 'New Balance', 175.00, 'The New Balance 990 is a premium running shoe with superior cushioning.'),
    (22, 'New Balance 990', 9.5, 'Grey', 'Suede', 0.85, 'New Balance', 175.00, 'The New Balance 990 is a premium running shoe with superior cushioning.'),
    (23, 'New Balance 990', 11.0, 'Navy', 'Suede', 0.85, 'New Balance', 175.00, 'The New Balance 990 is a premium running shoe with superior cushioning.'),
    (24, 'New Balance 990', 8.5, 'Black', 'Suede', 0.85, 'New Balance', 175.00, 'The New Balance 990 is a premium running shoe with superior cushioning.'),
    (25, 'Converse Chuck Taylor', 10.0, 'Black', 'Canvas', 0.60, 'Converse', 65.00, 'The Converse Chuck Taylor is an iconic sneaker loved worldwide.'),
    (26, 'Converse Chuck Taylor', 9.5, 'Red', 'Canvas', 0.60, 'Converse', 65.00, 'The Converse Chuck Taylor is an iconic sneaker loved worldwide.'),
    (27, 'Converse Chuck Taylor', 11.0, 'White', 'Canvas', 0.60, 'Converse', 65.00, 'The Converse Chuck Taylor is an iconic sneaker loved worldwide.'),
    (28, 'Converse Chuck Taylor', 8.5, 'Navy', 'Canvas', 0.60, 'Converse', 65.00, 'The Converse Chuck Taylor is an iconic sneaker loved worldwide.'),
    (29, 'Vans Old Skool', 10.0, 'Black', 'Canvas', 0.65, 'Vans', 70.00, 'The Vans Old Skool features classic skate style and durability.'),
    (30, 'Vans Old Skool', 9.5, 'Black', 'Canvas', 0.65, 'Vans', 70.00, 'The Vans Old Skool features classic skate style and durability.'),
    (31, 'Vans Old Skool', 11.0, 'Navy', 'Canvas', 0.65, 'Vans', 70.00, 'The Vans Old Skool features classic skate style and durability.'),
    (32, 'Vans Old Skool', 8.5, 'Red', 'Canvas', 0.65, 'Vans', 70.00, 'The Vans Old Skool features classic skate style and durability.'),
    (33, 'Asics Gel-Kayano', 10.0, 'Blue', 'Mesh', 0.80, 'Asics', 160.00, 'The Asics Gel-Kayano provides exceptional stability and support.'),
    (34, 'Asics Gel-Kayano', 9.5, 'Black', 'Mesh', 0.80, 'Asics', 160.00, 'The Asics Gel-Kayano provides exceptional stability and support.'),
    (35, 'Asics Gel-Kayano', 11.0, 'Grey', 'Mesh', 0.80, 'Asics', 160.00, 'The Asics Gel-Kayano provides exceptional stability and support.'),
    (36, 'Asics Gel-Kayano', 8.5, 'White', 'Mesh', 0.80, 'Asics', 160.00, 'The Asics Gel-Kayano provides exceptional stability and support.'),
    (37, 'Under Armour HOVR', 10.0, 'Black', 'Knit', 0.75, 'Under Armour', 140.00, 'The Under Armour HOVR delivers energy return and smooth ride.'),
    (38, 'Under Armour HOVR', 9.5, 'Red', 'Knit', 0.75, 'Under Armour', 140.00, 'The Under Armour HOVR delivers energy return and smooth ride.'),
    (39, 'Under Armour HOVR', 11.0, 'White', 'Knit', 0.75, 'Under Armour', 140.00, 'The Under Armour HOVR delivers energy return and smooth ride.'),
    (40, 'Under Armour HOVR', 8.5, 'Grey', 'Knit', 0.75, 'Under Armour', 140.00, 'The Under Armour HOVR delivers energy return and smooth ride.'),
    (41, 'Saucony Ride', 10.0, 'Blue', 'Mesh', 0.72, 'Saucony', 130.00, 'The Saucony Ride offers smooth transitions and responsive cushioning.'),
    (42, 'Saucony Ride', 9.5, 'Black', 'Mesh', 0.72, 'Saucony', 130.00, 'The Saucony Ride offers smooth transitions and responsive cushioning.'),
    (43, 'Saucony Ride', 11.0, 'Orange', 'Mesh', 0.72, 'Saucony', 130.00, 'The Saucony Ride offers smooth transitions and responsive cushioning.'),
    (44, 'Saucony Ride', 8.5, 'Grey', 'Mesh', 0.72, 'Saucony', 130.00, 'The Saucony Ride offers smooth transitions and responsive cushioning.'),
    (45, 'Brooks Ghost', 10.0, 'Black', 'Mesh', 0.78, 'Brooks', 150.00, 'The Brooks Ghost is a versatile neutral running shoe.'),
    (46, 'Brooks Ghost', 9.5, 'Blue', 'Mesh', 0.78, 'Brooks', 150.00, 'The Brooks Ghost is a versatile neutral running shoe.'),
    (47, 'Brooks Ghost', 11.0, 'White', 'Mesh', 0.78, 'Brooks', 150.00, 'The Brooks Ghost is a versatile neutral running shoe.'),
    (48, 'Brooks Ghost', 8.5, 'Grey', 'Mesh', 0.78, 'Brooks', 150.00, 'The Brooks Ghost is a versatile neutral running shoe.'),
    (49, 'Hoka Clifton', 10.0, 'White', 'Mesh', 0.68, 'Hoka', 145.00, 'The Hoka Clifton is lightweight with maximum cushioning.'),
    (50, 'Hoka Clifton', 9.5, 'Black', 'Mesh', 0.68, 'Hoka', 145.00, 'The Hoka Clifton is lightweight with maximum cushioning.'),
    (51, 'Hoka Clifton', 11.0, 'Blue', 'Mesh', 0.68, 'Hoka', 145.00, 'The Hoka Clifton is lightweight with maximum cushioning.'),
    (52, 'Hoka Clifton', 8.5, 'Grey', 'Mesh', 0.68, 'Hoka', 145.00, 'The Hoka Clifton is lightweight with maximum cushioning.'),
    (53, 'Salomon Speedcross', 10.0, 'Black', 'Synthetic', 0.82, 'Salomon', 135.00, 'The Salomon Speedcross excels in trail running performance.'),
    (54, 'Salomon Speedcross', 9.5, 'Blue', 'Synthetic', 0.82, 'Salomon', 135.00, 'The Salomon Speedcross excels in trail running performance.'),
    (55, 'Salomon Speedcross', 11.0, 'Red', 'Synthetic', 0.82, 'Salomon', 135.00, 'The Salomon Speedcross excels in trail running performance.'),
    (56, 'Salomon Speedcross', 8.5, 'Grey', 'Synthetic', 0.82, 'Salomon', 135.00, 'The Salomon Speedcross excels in trail running performance.'),
    (57, 'Mizuno Wave Rider', 10.0, 'Blue', 'Mesh', 0.76, 'Mizuno', 125.00, 'The Mizuno Wave Rider provides smooth and stable rides.'),
    (58, 'Mizuno Wave Rider', 9.5, 'Black', 'Mesh', 0.76, 'Mizuno', 125.00, 'The Mizuno Wave Rider provides smooth and stable rides.'),
    (59, 'Mizuno Wave Rider', 11.0, 'White', 'Mesh', 0.76, 'Mizuno', 125.00, 'The Mizuno Wave Rider provides smooth and stable rides.'),
    (60, 'Mizuno Wave Rider', 8.5, 'Orange', 'Mesh', 0.76, 'Mizuno', 125.00, 'The Mizuno Wave Rider provides smooth and stable rides.');
