FROM python:3.11.5-slim-bookworm

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app
COPY ./entrypoint.sh /code/entrypoint.sh

RUN chmod +x /code/entrypoint.sh

EXPOSE 8000
# have to use a shell script to run python file so that script runs during container startup and not during build time
CMD ["sh", "/code/entrypoint.sh"]

#RUN python app/memory_setup.py
#CMD ["fastapi", "run", "app/api_entrypoint.py", "--port", "8000"]